# Generated by Django 5.0.3 on 2024-03-11 10:41

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="listing/listing_images/",
                validators=[auctions.models.validate_image_size],
            ),
        ),
    ]
