# Generated by Django 5.0.3 on 2024-03-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_category_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
